repos:
  - repo: https://github.com/PyCQA/isort
    # rev: 5.12.0
    rev: 5.11.5
    hooks:
      - id: isort
        args: ["--line-length=120"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        args: [--max-line-length=120]
