# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint --rcfile=./.pylint.conf
        language: system
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/chengzhang/google-python-style-precommit-hook.git
    rev: 0f10b46c22c8c389ce6bc16d71a18c03c74d160c
    hooks:
    -   id: google-python-style
