# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x07\x65xample\"\x1b\n\x03\x46oo\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\"+\n\x03\x42\x61r\x12\t\n\x01z\x18\x01 \x01(\t\x12\x19\n\x03\x66oo\x18\x02 \x01(\x0b\x32\x0c.example.Foob\x06proto3')



_FOO = DESCRIPTOR.message_types_by_name['Foo']
_BAR = DESCRIPTOR.message_types_by_name['Bar']
Foo = _reflection.GeneratedProtocolMessageType('Foo', (_message.Message,), {
  'DESCRIPTOR' : _FOO,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:example.Foo)
  })
_sym_db.RegisterMessage(Foo)

Bar = _reflection.GeneratedProtocolMessageType('Bar', (_message.Message,), {
  'DESCRIPTOR' : _BAR,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:example.Bar)
  })
_sym_db.RegisterMessage(Bar)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FOO._serialized_start=23
  _FOO._serialized_end=50
  _BAR._serialized_start=52
  _BAR._serialized_end=95
# @@protoc_insertion_point(module_scope)
